import type { Metadata } from "next";
import { SiteNav } from "@/components/site-nav";
import { cmsFallbacks, getCms } from "@/lib/cms";
import { pageMetadata, organizationLd, SITE_URL } from "@/lib/seo";
export const metadata: Metadata = pageMetadata("Tentang Kami | Jogja Creative Production (JCP)", "Kenali PT Jogja Creative Production.", "/tentang");
const structuredData = { "@context": "https://schema.org", "@type": "AboutPage", name: "Tentang Jogja Creative Production", url: `${SITE_URL}/tentang`, about: organizationLd() };
export default async function AboutPage() { const content = await getCms("about", cmsFallbacks.about); const lines = (v: string) => v.split("\n").map((x, i) => <span key={`${x}-${i}`}>{i > 0 && <br />}{x}</span>); return <main className="about-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} /><SiteNav active="tentang" />
  <section className="about-hero shell"><p className="section-label">{content.heroLabel}</p><h1>{lines(content.heroTitle)}</h1><p>{content.heroIntro}</p></section>
  <section className="about-story"><div className="shell about-story-grid"><p className="section-label">{content.storyLabel}</p><div><h2>{lines(content.storyTitle)}</h2><p>{content.storyCopy}</p><p>{content.storyCopy2}</p></div></div></section>
  <section className="company-profile shell"><p className="section-label">{content.profileLabel}</p><div className="company-profile-intro"><h2>{lines(content.profileTitle)}</h2><div><p>{content.profileCopy1}</p><p>{content.profileCopy2}</p></div></div><div className="company-units">{content.units.map((unit) => <article key={unit.name}><span>{unit.name}</span><p>{unit.description}</p><small>{unit.tags}</small></article>)}</div></section>
  <section className="vision shell"><p className="section-label">{content.directionLabel}</p><div><span>Vision</span><h2>{content.vision}</h2></div><div className="mission"><span>Mission</span><ol>{content.mission.map((item) => <li key={item}>{item}</li>)}</ol></div></section>
  <section className="values"><div className="shell"><div className="values-heading"><div><p className="section-label">{content.valuesLabel}</p><p className="values-lede">{content.valuesIntro}</p></div><h2>{lines(content.valuesTitle)}</h2></div><div className="value-grid">{content.values.map((value) => <article key={value.number} data-number={value.number}><span>{value.number}</span><h3>{value.title}</h3><p>{value.description}</p></article>)}</div></div></section>
  <section className="team shell"><div className="team-heading"><p className="section-label">{content.teamLabel}</p><h2>{lines(content.teamTitle)}</h2></div><div className="team-list">{content.teams.map((team) => <article key={team.group}><span>{team.group}</span><h3>{team.names}</h3><p>{team.role}</p></article>)}</div></section>
  <section className="company-assurance"><div className="shell"><p className="section-label">{content.assuranceLabel}</p><div className="assurance-grid"><h2>{lines(content.assuranceTitle)}</h2><div><p>{content.assuranceCopy1}</p><p>{content.assuranceCopy2}</p></div></div><div className="legal-strip">{content.legal.map((item) => <article key={item.label}><span>{item.label}</span><p>{item.text}</p></article>)}</div></div></section>
</main>; }
