"use client";
import { useLayoutEffect, useRef, useState } from "react";
import { useMotionValueEvent, useScroll } from "framer-motion";
import { cmsFallbacks } from "@/lib/cms";

type NavItem = { label: string; href: string; dropdown?: boolean };
type Navigation = { announcement: string; items: readonly NavItem[]; cta: string };
const services = [["01", "North Production", "Foto, video & dokumentasi", "north-production"], ["02", "North Creative", "Branding & social media", "north-creative"], ["03", "North Photobooth", "Photobooth untuk event", "north-booth"], ["04", "Virtual Tour 360", "Ruang yang bisa dijelajahi", "virtual-tour-360"], ["05", "Drone Training", "Pelatihan drone profesional", "drone-training"], ["06", "AI Kreasi Cerdas", "Solusi AI sesuai kebutuhan", "ai-kreasi-cerdas"]] as const;
type SiteNavProps = { active?: "tentang" | "layanan" | "portfolio" | "hubungi" };
const activeFor = (href: string, active?: string) => (href.includes("tentang") ? active === "tentang" : href.includes("layanan") ? active === "layanan" : href.includes("portfolio") ? active === "portfolio" : false);

export function SiteNav({ active }: SiteNavProps) {
  const [servicesOpen, setServicesOpen] = useState(false); const [announcementOpen, setAnnouncementOpen] = useState<boolean | null>(null); const [menuOpen, setMenuOpen] = useState(false); const [navVisible, setNavVisible] = useState(true); const [landingPastHero, setLandingPastHero] = useState(false); const [navigation, setNavigation] = useState<Navigation>(cmsFallbacks.navigation as Navigation); const previousScroll = useRef(0); const { scrollY } = useScroll();
  useLayoutEffect(() => { setAnnouncementOpen(localStorage.getItem("jcp-announcement-dismissed") !== "true"); fetch("/api/public/content?key=navigation").then((r) => r.ok ? r.json() : null).then((value) => { if (value?.items?.length) setNavigation(value); }).catch(() => undefined); const hero = document.querySelector(".hero-lines-hero"); setLandingPastHero(Boolean(hero && hero.getBoundingClientRect().bottom <= 110)); }, []);
  useMotionValueEvent(scrollY, "change", (currentScroll) => { const hero = document.querySelector(".hero-lines-hero"); setLandingPastHero(Boolean(hero && hero.getBoundingClientRect().bottom <= 110)); if (Math.abs(currentScroll - previousScroll.current) < 8) return; const banner = document.querySelector(".footer-banner"); const headerHeight = document.querySelector(".site-header")?.getBoundingClientRect().height ?? 96; const bannerUnderNav = Boolean(banner && banner.getBoundingClientRect().top < headerHeight && banner.getBoundingClientRect().bottom > 0); setNavVisible(currentScroll < 72 || (!bannerUnderNav && currentScroll < previousScroll.current)); previousScroll.current = currentScroll; });
  return <header className={`site-header${navVisible ? "" : " is-nav-hidden"}${landingPastHero ? " is-landing-scrolled" : ""}`}>
    {announcementOpen === true && <div className="nav-announcement"><a href="/hubungi">{navigation.announcement} <b>→</b></a><button type="button" aria-label="Tutup pengumuman" onClick={() => { setAnnouncementOpen(false); localStorage.setItem("jcp-announcement-dismissed", "true"); }}>×</button></div>}
    <nav className="nav shell" aria-label="Navigasi utama"><a className="wordmark" href="/" aria-label="Jogja Creative Production"><img src="/jcp-logo-nav.png" alt="JCP - Jogja Creative Production" width="288" height="288" loading="eager" /></a><button className="mobile-menu-toggle" type="button" aria-label={menuOpen ? "Tutup menu" : "Buka menu"} aria-expanded={menuOpen} onClick={() => setMenuOpen((open) => !open)}>Menu</button><div className={`nav-links${menuOpen ? " mobile-open" : ""}`}>
      {navigation.items.map((item) => item.dropdown ? <div className="nav-dropdown" key={item.href} onMouseEnter={() => { if (window.matchMedia("(hover: hover)").matches) setServicesOpen(true); }} onMouseLeave={() => { if (window.matchMedia("(hover: hover)").matches) setServicesOpen(false); }}><button className={activeFor(item.href, active) ? "active" : ""} type="button" onClick={() => setServicesOpen((open) => !open)}>{item.label} <span>↓</span></button>{servicesOpen && <div className="services-menu"><div className="services-menu-intro"><span>(JCP SERVICES)</span><strong>Choose your<br />creative lane.</strong><a href="/layanan" onClick={() => setServicesOpen(false)}>Lihat semua layanan <b>↗</b></a></div><div className="services-menu-grid">{services.map(([number, title, description, slug]) => <a href={`/layanan/${slug}`} key={slug} onClick={() => setServicesOpen(false)}><span>{number}</span><strong>{title}</strong><small>{description}</small><b>↗</b></a>)}</div></div>}</div> : <a className={activeFor(item.href, active) ? "active" : ""} href={item.href} key={`${item.label}-${item.href}`} onClick={() => setMenuOpen(false)}>{item.label}</a>)}
      <a className="nav-mobile-cta" href="/hubungi" onClick={() => setMenuOpen(false)}>{navigation.cta} <i>↗</i></a></div><a className={`nav-cta${active === "hubungi" ? " active-cta" : ""}`} href="/hubungi">{navigation.cta} <i>↗</i></a></nav>
  </header>;
}
