import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Image from "next/image";
import { SiteNav } from "@/components/site-nav";
import { getImageDims } from "@/lib/image-dims";
import { pageMetadata, SITE_URL } from "@/lib/seo";

type GalleryItem = { image?:string; title:string; category:string; tone:string; video?:string; poster?:string; wide?:boolean };
type ServiceDetail = { name:string; label:string; intro:string; audience:string; offers:string[]; points:string[]; faq:string; gallery?:GalleryItem[]; instagram?:string; ig?:string };

const details: Record<string, ServiceDetail> = {
  "north-production": { name:"North Production", label:"Photo & video production", intro:"North Production adalah layanan produksi foto dan video profesional yang membantu brand, perusahaan, hotel, dan event menyampaikan cerita visual yang kuat, estetik, dan berdampak. Kami menghadirkan konten visual yang tidak hanya indah, tetapi juga efektif untuk kebutuhan pemasaran dan branding. Dengan pendekatan kreatif dan berbasis data, North Production memastikan setiap konten tidak hanya menarik secara visual, tetapi juga efektif dalam meningkatkan engagement, awareness, dan kepercayaan audiens.", audience:"Brand, perusahaan, hotel, dan event yang membutuhkan konten visual profesional untuk kebutuhan pemasaran, branding, dan komunikasi.", offers:["Foto produk","Foto-video event","Foto portrait & corporate","Foto-video brand & lifestyle","Foto-video komersial dan iklan","Foto-video company profile & bentuk visual digital lainnya"], points:["Cerita visual yang kuat, estetik, dan berdampak","Pendekatan kreatif dan berbasis data","Konten untuk mendukung engagement, awareness, dan kepercayaan audiens"], faq:"Ruang lingkup produksi disusun sesuai tujuan komunikasi, kebutuhan visual, dan platform publikasi brand.", instagram:"https://www.instagram.com/north.production?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", ig:"@north.production", gallery:[{ image:"/services/north-production-gallery/north-production-1.jpg", title:"Brand Lifestyle Shoot", category:"Photo Production", tone:"orange" },{ image:"/services/north-production-gallery/north-production-2.jpg", title:"Corporate Profile", category:"Video Production", tone:"ink" },{ image:"/services/north-production-gallery/north-production-3.jpg", title:"Event Documentation", category:"Photo Production", tone:"clay" },{ image:"/services/north-production-gallery/north-production-4.jpg", title:"Product Visual Story", category:"Photo Production", tone:"sage" },{ image:"/services/north-production-gallery/north-production-5.jpg", title:"Commercial Content", category:"Video Production", tone:"sun" }] },
  "north-creative": { name:"North Creative", label:"Social media management", intro:"North Creative merupakan layanan desain dan branding yang membantu bisnis membangun identitas visual yang kuat dan konsisten. Kami menciptakan materi grafis yang relevan, estetis, dan strategis, mulai dari perancangan logo, brand identity, hingga kebutuhan konten visual. Setiap desain dibuat untuk menyampaikan pesan dengan jelas, meningkatkan citra brand, dan memberikan kesan profesional di setiap platform komunikasi. Dengan menggabungkan riset, kreativitas, dan pendekatan strategis, North Creative hadir untuk menciptakan visual yang tidak hanya menarik secara estetika, tetapi juga mampu memperkuat positioning brand di mata audiens.", audience:"Bisnis yang ingin membangun identitas visual yang kuat, konsisten, dan relevan di setiap platform komunikasi.", offers:["Perancangan logo dan brand identity","Desain materi grafis dan konten visual","Perencanaan konten dan copywriting","Social media management"], points:["Desain dibuat untuk memperjelas pesan brand","Riset, kreativitas, dan pendekatan strategis","Visual yang memperkuat positioning di mata audiens"], faq:"Bringing ideas & innovation to life through technology.", instagram:"https://www.instagram.com/north.ive?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", ig:"@north.ive", gallery:[{ image:"/services/north-creative-gallery/north-creative-1.jpg", title:"Multi-Platform Presence", category:"Social Media", tone:"ink" },{ image:"/services/north-creative-gallery/north-creative-2.jpg", title:"Content Planning", category:"Social Media", tone:"sun" },{ image:"/services/north-creative-gallery/north-creative-3.jpg", title:"Campaign Performance", category:"Content Strategy", tone:"clay" },{ image:"/services/north-creative-gallery/north-creative-4.jpg", title:"Audience Engagement", category:"Social Media", tone:"sage" },{ image:"/services/north-creative-gallery/north-creative-5.jpg", title:"Brand Visual Identity", category:"Branding", tone:"orange" }] },
  "north-booth": { name:"North Photobooth", label:"Event documentation", intro:"Layanan dokumentasi event yang dirancang untuk menangkap momen secara profesional dan menyenangkan. Dengan kamera serta pencahayaan berkualitas, kami menyediakan booth yang mudah digunakan, cepat, dan menghasilkan foto maupun video siap dibagikan secara instan.", audience:"Event perusahaan, gathering, festival, hingga event promosi yang membutuhkan dokumentasi berkualitas sekaligus pengalaman interaktif bagi pengunjung.", offers:["Photo booth & video booth untuk dokumentasi event","Desain booth modern yang dapat disesuaikan dengan tema dan identitas acara","Hasil foto dan video berkualitas tinggi","Instant sharing ke media sosial"], points:["Kualitas kamera profesional","Desain booth modern & customizable","Instant sharing","Beragam mode dan efek kreatif","Tim operator profesional"], faq:"Konfigurasi booth disesuaikan dengan venue, tema acara, kebutuhan branding, dan durasi event.", instagram:"https://www.instagram.com/northphoto.id?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", ig:"@northphoto.id", gallery:[{ video:"/services/north-booth-gallery/north-booth-360.mp4", poster:"/services/north-booth-gallery/north-booth-1.jpg", image:"/services/north-booth-gallery/north-booth-1.jpg", title:"360 Video Booth", category:"Motion / 360 Capture", tone:"orange", wide:true },{ image:"/services/north-booth-gallery/north-booth-1.jpg", title:"360 Booth Activation", category:"Event Experience", tone:"orange" },{ image:"/services/north-booth-gallery/north-booth-2.jpg", title:"Guest Moments", category:"Event Documentation", tone:"ink" },{ image:"/services/north-booth-gallery/north-booth-3.jpg", title:"Instant Capture", category:"Photo Booth", tone:"clay" },{ image:"/services/north-booth-gallery/north-booth-4.jpg", title:"Group Session", category:"Event Experience", tone:"sage" },{ image:"/services/north-booth-gallery/north-booth-5.jpg", title:"Props & Play", category:"Photo Booth", tone:"sun" }] },
  "virtual-tour-360": { name:"North Virtual Tour 360", label:"Immersive spaces", intro:"Layanan tour virtual interaktif yang memungkinkan pengguna menjelajahi ruang atau fasilitas secara 360°. Dengan kualitas visual tinggi dan navigasi yang mudah, klien dapat menampilkan lokasi mereka secara menarik dan informatif, kapan saja dan dari mana saja.", audience:"Properti, hotel, sekolah, pabrik, showroom, dan destinasi wisata yang ingin memberikan pengalaman kunjungan virtual dengan detail yang realistis dan profesional.", offers:["Pemotretan 360° berkualitas tinggi","Navigasi interaktif","Custom branding interface","Cross-platform ready"], points:["Menyajikan ruang dan fasilitas secara menarik serta informatif","Memudahkan calon pengunjung menjelajah dari mana saja","Memberikan pengalaman kunjungan virtual yang realistis dan profesional"], faq:"Cakupan titik panorama dan elemen interaktif ditentukan melalui survei lokasi dan tujuan pengalaman.", instagram:"https://www.instagram.com/north.virtual360?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", ig:"@north.virtual360", gallery:[{ video:"/services/virtual-tour-360-gallery/virtual-tour-360-1.mp4", poster:"/services/virtual-tour-360-gallery/virtual-tour-360-1.jpg", image:"/services/virtual-tour-360-gallery/virtual-tour-360-1.jpg", title:"360 Experience", category:"360 Capture", tone:"orange" },{ image:"/services/virtual-tour-360-gallery/virtual-tour-360-1.jpg", title:"Interactive Walkthrough", category:"360 Tour", tone:"ink" },{ image:"/services/virtual-tour-360-gallery/virtual-tour-360-2.jpg", title:"Immersive Journey", category:"Virtual Experience", tone:"clay" },{ video:"/services/virtual-tour-360-gallery/virtual-tour-360-2.mp4", title:"Guided Experience", category:"360 Tour", tone:"sage" },{ image:"/services/virtual-tour-360-gallery/virtual-tour-360-3.jpg", title:"Discover Every Corner", category:"Virtual Tour", tone:"sun" },{ video:"/services/virtual-tour-360-gallery/virtual-tour-360-3.mp4", title:"Smooth Navigation", category:"360 Experience", tone:"ink" },{ image:"/services/virtual-tour-360-gallery/virtual-tour-360-4.jpg", title:"Seamless Story", category:"Virtual Tour", tone:"clay" }] },
  "drone-training": { name:"Indonesia Drone Training Centre", label:"Training & safety", intro:"Layanan pelatihan drone yang berfokus pada keterampilan terbang, pengoperasian kamera, dan keselamatan penerbangan. Peserta belajar langsung melalui praktik di lapangan dengan panduan instruktur berpengalaman, mulai dari tingkat dasar hingga mahir. Pelatihan ini dirancang agar setiap peserta mampu menguasai teknik penerbangan dengan aman, menghasilkan footage yang stabil, serta memahami prosedur operasional sesuai standar.", audience:"Hobi, dokumentasi profesional, hingga kebutuhan industri yang ingin meningkatkan keterampilan pengoperasian drone secara terarah.", offers:["Pelatihan dari tingkat dasar hingga mahir","Keterampilan terbang","Pengoperasian kamera","Keselamatan penerbangan","Praktik langsung di lapangan","Prosedur operasional sesuai standar"], points:["Instruktur berpengalaman","Fokus pada teknik penerbangan yang aman","Membantu peserta menghasilkan footage yang stabil"], faq:"Materi dan durasi pelatihan menyesuaikan kemampuan awal peserta serta kebutuhan organisasi.", instagram:"https://www.instagram.com/idtc.drone?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==", ig:"@idtc.drone",gallery:[{ image:"/services/drone-training-gallery/drone-training-1.jpg", title:"Pelatihan Drone Mapping untuk Masyarakat Umum", category:"Drone Training", tone:"orange" },{ image:"/services/drone-training-gallery/drone-training-2.jpg", title:"Berbagai Jenis Drone untuk Pelatihan", category:"Drone Training", tone:"ink" },{ image:"/services/drone-training-gallery/drone-training-3.jpg", title:"Pelatihan Drone bersama Komunitas Mahasiswa", category:"Drone Training", tone:"clay" },{ image:"/services/drone-training-gallery/drone-training-4.jpg", title:"Pelatihan Drone untuk Tanggap Bencana", category:"Drone Training", tone:"sage" },{ image:"/services/drone-training-gallery/drone-training-5.jpg", title:"Pelatihan Drone Dinas Tenaga Kerja Kabupaten Sleman", category:"Drone Training", tone:"sun" },{ image:"/services/drone-training-gallery/drone-training-6.jpg", title:"Pelatihan Drone Pertanian", category:"Drone Training", tone:"paper" }] },
  "ai-kreasi-cerdas": { name:"AI Kreasi Cerdas", label:"AI creative solutions", intro:"Solusi menggunakan AI tools yang dirancang dinamis sesuai kebutuhan setiap pelanggan.", audience:"Bisnis dan organisasi yang ingin mengeksplorasi pemanfaatan AI untuk kebutuhan kreatif maupun alur kerja yang lebih sesuai dengan tujuan mereka.", offers:["Pemetaan kebutuhan pelanggan","Rancangan solusi berbasis AI tools","Konfigurasi yang disesuaikan dengan kebutuhan","Pendampingan penerapan solusi"], points:["Pendekatan dinamis sesuai kebutuhan","Berangkat dari tujuan dan konteks pelanggan","Solusi yang dapat disesuaikan seiring kebutuhan berkembang"], faq:"Setiap solusi dirancang melalui diskusi kebutuhan agar AI tools yang digunakan relevan dengan tujuan pelanggan.",gallery:[{ image:"/services/ai-kreasi-cerdas-gallery/ai-kreasi-cerdas-01.jpg", title:"AI Automation", category:"AI Automation", tone:"orange" },{ image:"/services/ai-kreasi-cerdas-gallery/ai-kreasi-cerdas-02.jpg", title:"Chatbot", category:"AI Design", tone:"ink" },{ video:"/services/ai-kreasi-cerdas-gallery/ai-kreasi-cerdas-01.mp4", poster:"/services/ai-kreasi-cerdas-gallery/ai-kreasi-cerdas-01.jpg", title:"AI Workflow", category:"AI Process", tone:"clay" },{ image:"/services/ai-kreasi-cerdas-gallery/ai-kreasi-cerdas-03.jpg", title:"Content Generation", category:"AI Content", tone:"sage" },{ image:"/services/ai-kreasi-cerdas-gallery/ai-kreasi-cerdas-04.jpg", title:"Modern Interior", category:"AI Styling", tone:"sun" }] },
};

const serviceTitles: Record<string, string> = {
  "north-production": "North Production | Jasa Foto & Video Profesional Yogyakarta",
  "north-creative": "North Creative | Jasa Branding & Social Media Management",
  "north-booth": "North Photobooth | Sewa Photobooth & Videobooth Event di Jogja",
  "virtual-tour-360": "Virtual Tour 360 | Jasa Foto Panorama 360° Properti & Hotel",
  "drone-training": "Drone Training Centre | Pelatihan Drone Profesional di Yogyakarta",
  "ai-kreasi-cerdas": "AI Kreasi Cerdas | Solusi AI untuk Bisnis: Chatbot, Otomasi, Konten",
};

const truncate = (text: string, max = 158) => (text.length <= max ? text : `${text.slice(0, max - 1).trimEnd()}…`);

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const service = details[slug as keyof typeof details];
  if (!service) return {};
  return pageMetadata(serviceTitles[slug] ?? service.name, `${service.label}. ${truncate(service.intro)}`, `/layanan/${slug}`);
}

export function generateStaticParams(){ return Object.keys(details).map((slug)=>({slug})); }
export default async function ServiceDetail({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const service=details[slug as keyof typeof details]; if(!service) notFound(); const ld = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Service",
        name: service.name,
        description: service.intro,
        url: `${SITE_URL}/layanan/${slug}`,
        provider: { "@type": "Organization", name: "PT Jogja Creative Production", url: SITE_URL },
        areaServed: "Yogyakarta, Indonesia",
        audience: { "@type": "Audience", name: service.audience },
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Beranda", item: SITE_URL },
          { "@type": "ListItem", position: 2, name: "Layanan", item: `${SITE_URL}/layanan` },
          { "@type": "ListItem", position: 3, name: service.name, item: `${SITE_URL}/layanan/${slug}` },
        ],
      },
      {
        "@type": "FAQPage",
        mainEntity: [{ "@type": "Question", name: `Apa saja yang perlu diketahui sebelum menggunakan layanan ${service.name}?`, acceptedAnswer: { "@type": "Answer", text: service.faq } }],
      },
    ],
  };
  return <main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(ld) }} /><SiteNav active="layanan" /><div className="service-detail shell"><p className="section-label">{service.label}</p><h1>{service.name}</h1><p className="detail-intro">{service.intro}</p><section><span>Untuk siapa</span><p>{service.audience}</p></section><section><span>Yang kami kerjakan</span><ul>{service.offers.map(x=><li key={x}>{x}</li>)}</ul></section><section><span>Kenapa JCP</span><ul>{service.points.map(x=><li key={x}>{x}</li>)}</ul></section><section><span>Info penting</span><p>{service.faq}</p></section>{service.gallery && <section className="service-gallery"><p className="section-label">(Selected work)</p><div className={`service-gallery-grid ${service.gallery.some((g:any)=>g.wide)?"":"is-masonry"}`}>{(service.gallery as GalleryItem[]).map((item, i)=><article className={`service-gallery-card ${item.tone}${item.wide?" is-wide":""}`} key={item.video ?? item.image}>{item.video ? <div className="service-gallery-art is-video"><video src={item.video} poster={item.poster} autoPlay muted loop playsInline preload="metadata" aria-label={item.title} /><span>{String(i+1).padStart(2,"0")}</span><em>JCP</em></div> : <div className="service-gallery-art"><Image src={item.image!} alt={item.title} width={getImageDims(item.image!).width} height={getImageDims(item.image!).height} sizes="(max-width: 720px) 100vw, 50vw" loading="lazy" /><span>{String(i+1).padStart(2,"0")}</span><em>JCP</em></div>}<div className="service-gallery-copy"><p>{item.category}</p><h3>{item.title}</h3></div></article>)}</div></section>}{service.instagram && <section className="service-social"><span>Instagram</span><a href={service.instagram} target="_blank" rel="noreferrer">{service.ig} <b>↗︎</b></a></section>}<a className="detail-cta" href="/hubungi">Diskusikan kebutuhan Anda ↗︎</a></div></main>; }
