import Link from "next/link";
import { notFound } from "next/navigation";

const details = {
  "north-production": { name:"North Production", label:"Photo & video production", intro:"Cerita visual yang membuat brand, bisnis, dan event terasa lebih hidup.", audience:"Brand, perusahaan, hotel, hingga event yang membutuhkan dokumentasi dengan arah kreatif yang jelas.", offers:["Foto produk, portrait, dan corporate","Foto & video event","Company profile dan campaign video","Aftermovie, reels, dan konten digital"], points:["Peralatan dan teknik produksi profesional","Siap untuk social media, laporan, presentasi, dan PR","Bisa mengikuti moodboard atau referensi visual klien"], faq:"Estimasi highlight foto/video 3–7 hari kerja; tersedia opsi same-day edit dan liputan luar kota." },
  "north-creative": { name:"North Creative", label:"Branding & social media", intro:"Identitas dan konten yang memberi brand Anda arah untuk tumbuh.", audience:"Bisnis yang ingin tampil konsisten, relevan, dan mudah dikenali di setiap touchpoint.", offers:["Perencanaan konten","Desain visual dan brand identity","Copywriting","Posting rutin dan social media management"], points:["Visual dibuat strategis, bukan hanya estetis","Identitas yang konsisten lintas platform","Riset dan kreativitas untuk memperkuat positioning"], faq:"Ruang lingkup, frekuensi konten, dan proses persetujuan disusun bersama sesuai kebutuhan brand." },
  "north-booth": { name:"North Photo & Video Booth", label:"Event experience", intro:"Momen event yang mudah dibagikan, seru dialami, dan sulit dilupakan.", audience:"Event perusahaan, gathering, festival, dan aktivitas promosi yang ingin meninggalkan pengalaman nyata.", offers:["Photobooth & videobooth","Desain booth yang customizable","Instant sharing","Beragam mode dan efek kreatif"], points:["Kamera dan pencahayaan berkualitas","Operator profesional di lokasi","Hasil siap dibagikan secara instan"], faq:"Konfigurasi booth menyesuaikan venue, tema acara, kebutuhan branding, dan durasi event." },
  "virtual-tour-360": { name:"North Virtual Tour 360", label:"Immersive spaces", intro:"Ruang yang bisa dikunjungi sebelum orang datang ke sana.", audience:"Properti, hotel, sekolah, pabrik, showroom, dan destinasi wisata.", offers:["Pemotretan 360° berkualitas tinggi","Navigasi interaktif","Custom branding interface","Cross-platform ready"], points:["Menampilkan ruang dan fasilitas dengan detail visual tinggi","Dapat diakses kapan saja dari berbagai perangkat","Memberikan pengalaman kunjungan yang realistis"], faq:"Cakupan titik panorama dan elemen interaktif ditentukan melalui survey lokasi dan tujuan pengalaman." },
  "drone-training": { name:"Indonesia Drone Training Centre", label:"Training & safety", intro:"Terbang lebih aman, merekam lebih mantap, dan memahami standar kerja di lapangan.", audience:"Pemula, hobi, dokumentasi profesional, hingga kebutuhan industri.", offers:["Pelatihan pemula hingga mahir","Keterampilan penerbangan","Pengoperasian kamera","Keselamatan dan praktik lapangan"], points:["Instruktur berpengalaman","Fokus pada praktik langsung","Membantu peserta menghasilkan footage yang stabil"], faq:"Materi dan durasi pelatihan menyesuaikan kemampuan awal peserta serta kebutuhan organisasi." },
};

export function generateStaticParams(){ return Object.keys(details).map((slug)=>({slug})); }
export default async function ServiceDetail({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const service=details[slug as keyof typeof details]; if(!service) notFound(); return <main className="service-detail shell"><Link href="/layanan" className="back-link">← Semua layanan</Link><p className="section-label">{service.label}</p><h1>{service.name}</h1><p className="detail-intro">{service.intro}</p><section><span>Untuk siapa</span><p>{service.audience}</p></section><section><span>Yang kami kerjakan</span><ul>{service.offers.map(x=><li key={x}>{x}</li>)}</ul></section><section><span>Kenapa JCP</span><ul>{service.points.map(x=><li key={x}>{x}</li>)}</ul></section><section><span>Info penting</span><p>{service.faq}</p></section><a className="detail-cta" href="/hubungi">Diskusikan kebutuhan Anda ↗</a></main>; }
