import { notFound } from "next/navigation";
import { SiteNav } from "@/components/site-nav";

const details = {
  "north-production": { name:"North Production", label:"Photo & video production", intro:"Cerita visual yang membuat brand, bisnis, dan event terasa lebih hidup.", audience:"Brand, perusahaan, hotel, hingga event yang membutuhkan dokumentasi dengan arah kreatif yang jelas.", offers:["Foto produk, portrait, dan corporate","Foto & video event","Company profile dan campaign video","Aftermovie, reels, dan konten digital"], points:["Peralatan dan teknik produksi profesional","Siap untuk social media, laporan, presentasi, dan PR","Bisa mengikuti moodboard atau referensi visual klien"], faq:"Estimasi highlight foto/video 3–7 hari kerja; tersedia opsi same-day edit dan liputan luar kota." },
  "north-creative": { name:"North Creative", label:"Social media management", intro:"North Creative merupakan layanan desain dan branding yang membantu bisnis membangun identitas visual yang kuat dan konsisten. Kami menciptakan materi grafis yang relevan, estetis, dan strategis, mulai dari perancangan logo, brand identity, hingga kebutuhan konten visual.", audience:"Bisnis yang ingin menyampaikan pesan dengan jelas, meningkatkan citra brand, dan meninggalkan kesan profesional di setiap platform komunikasi.", offers:["Perancangan logo dan brand identity","Desain materi grafis dan konten visual","Perencanaan konten dan copywriting","Social media management"], points:["Desain dibuat untuk memperjelas pesan brand","Riset, kreativitas, dan pendekatan strategis","Visual yang memperkuat positioning di mata audiens"], faq:"Bringing ideas & innovation to life through technology." },
  "north-booth": { name:"North Photo & Video Booth", label:"Event documentation", intro:"Layanan dokumentasi event yang dirancang untuk menangkap momen secara profesional dan menyenangkan. Dengan kamera serta pencahayaan berkualitas, kami menyediakan booth yang mudah digunakan, cepat, dan menghasilkan foto maupun video siap dibagikan secara instan.", audience:"Event perusahaan, gathering, festival, hingga event promosi yang membutuhkan dokumentasi berkualitas sekaligus pengalaman interaktif bagi pengunjung.", offers:["Photo booth & video booth untuk dokumentasi event","Desain booth modern yang dapat disesuaikan dengan tema dan identitas acara","Hasil foto dan video berkualitas tinggi","Instant sharing ke media sosial"], points:["Kualitas kamera profesional","Desain booth modern & customizable","Instant sharing","Beragam mode dan efek kreatif","Tim operator profesional"], faq:"Konfigurasi booth disesuaikan dengan venue, tema acara, kebutuhan branding, dan durasi event." },
  "virtual-tour-360": { name:"North Virtual Tour 360", label:"Immersive spaces", intro:"Layanan tour virtual interaktif yang memungkinkan pengguna menjelajahi ruang atau fasilitas secara 360°. Dengan kualitas visual tinggi dan navigasi yang mudah, klien dapat menampilkan lokasi mereka secara menarik dan informatif, kapan saja dan dari mana saja.", audience:"Properti, hotel, sekolah, pabrik, showroom, dan destinasi wisata yang ingin memberikan pengalaman kunjungan virtual dengan detail yang realistis dan profesional.", offers:["Pemotretan 360° berkualitas tinggi","Navigasi interaktif","Custom branding interface","Cross-platform ready"], points:["Menyajikan ruang dan fasilitas secara menarik serta informatif","Memudahkan calon pengunjung menjelajah dari mana saja","Memberikan pengalaman kunjungan virtual yang realistis dan profesional"], faq:"Cakupan titik panorama dan elemen interaktif ditentukan melalui survei lokasi dan tujuan pengalaman." },
  "drone-training": { name:"Indonesia Drone Training Centre", label:"Training & safety", intro:"Terbang lebih aman, merekam lebih mantap, dan memahami standar kerja di lapangan.", audience:"Pemula, hobi, dokumentasi profesional, hingga kebutuhan industri.", offers:["Pelatihan pemula hingga mahir","Keterampilan penerbangan","Pengoperasian kamera","Keselamatan dan praktik lapangan"], points:["Instruktur berpengalaman","Fokus pada praktik langsung","Membantu peserta menghasilkan footage yang stabil"], faq:"Materi dan durasi pelatihan menyesuaikan kemampuan awal peserta serta kebutuhan organisasi." },
  "ai-kreasi-cerdas": { name:"AI Kreasi Cerdas", label:"AI creative solutions", intro:"Solusi menggunakan AI tools yang dirancang dinamis sesuai kebutuhan setiap pelanggan.", audience:"Bisnis dan organisasi yang ingin mengeksplorasi pemanfaatan AI untuk kebutuhan kreatif maupun alur kerja yang lebih sesuai dengan tujuan mereka.", offers:["Pemetaan kebutuhan pelanggan","Rancangan solusi berbasis AI tools","Konfigurasi yang disesuaikan dengan kebutuhan","Pendampingan penerapan solusi"], points:["Pendekatan dinamis sesuai kebutuhan","Berangkat dari tujuan dan konteks pelanggan","Solusi yang dapat disesuaikan seiring kebutuhan berkembang"], faq:"Setiap solusi dirancang melalui diskusi kebutuhan agar AI tools yang digunakan relevan dengan tujuan pelanggan." },
};

export function generateStaticParams(){ return Object.keys(details).map((slug)=>({slug})); }
export default async function ServiceDetail({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const service=details[slug as keyof typeof details]; if(!service) notFound(); return <main><SiteNav active="layanan" /><div className="service-detail shell"><p className="section-label">{service.label}</p><h1>{service.name}</h1><p className="detail-intro">{service.intro}</p><section><span>Untuk siapa</span><p>{service.audience}</p></section><section><span>Yang kami kerjakan</span><ul>{service.offers.map(x=><li key={x}>{x}</li>)}</ul></section><section><span>Kenapa JCP</span><ul>{service.points.map(x=><li key={x}>{x}</li>)}</ul></section><section><span>Info penting</span><p>{service.faq}</p></section><a className="detail-cta" href="/hubungi">Diskusikan kebutuhan Anda ↗</a></div></main>; }
